# Generated by Django 5.1.5 on 2025-01-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_storecontact_delete_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='storecontact',
        ),
        migrations.AlterField(
            model_name='storeinstruments',
            name='image',
            field=models.ImageField(upload_to='store_images/'),
        ),
    ]
