# Generated by Django 5.1.5 on 2025-01-27 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_cart_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeinstruments',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='instruments/'),
        ),
    ]
