# Generated by Django 5.1.5 on 2025-01-27 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_cart_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='instrument',
            new_name='product',
        ),
    ]
