# Generated by Django 5.1.5 on 2025-01-27 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_instrument_cart_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
